---
on: push

jobs:
  pytest-jobcreator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd job_creator
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Run pytest
        run: pytest ./job_creator --random-order --random-order-bucket=global --ignore=test/database/test_db_updater_integration.py --cov --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pytest-jobwatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd job_watcher
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Run pytest
        run: pytest ./job_watcher --random-order --random-order-bucket=global --ignore=test/database/test_db_updater_integration.py --cov --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
